spring:
  application:
    name: Fitfusion
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: fitfusion
    password: zxcv1234
#개발 중 템플릿 캐싱 끄기 !!!!!!! commit 전에 확인하기#
  thymeleaf:
    cache: false

server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: com.fitfusion.vo