spring:
  application:
    name: Fitfusion
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: fitfusion
    password: zxcv1234
  config:
    import:
      - classpath:securekey.yml
server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: com.fitfusion.vo
